M48
; DRILL file {KiCad (6.0.2)} date Sun Apr 10 14:27:58 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-04-10T14:27:58+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X94.5Y-117.855
X97.5Y-117.855
T2
X98.542Y-84.162
X98.542Y-94.562
T0
M30
