M48
; DRILL file {KiCad (6.0.2)} date Sun Mar  6 12:06:21 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-06T12:06:21+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X126.32Y-62.41
X129.32Y-62.41
T2
X122.11Y-49.0
X122.11Y-59.0
T0
M30
