M48
; DRILL file {KiCad (6.0.0)} date Tue Feb  8 22:33:15 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-02-08T22:33:15+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X126.32Y-62.41
X129.32Y-62.41
T2
X122.105Y-48.98
X122.105Y-58.98
T0
M30
